---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbC7fGQkGTjXERSAwLq7co5QXvahoXdG93m/Zx/+W1v+eme1ZohTCyi41MkcAJDr2KHSibwo6PE7WWjgYFAsZg/PNE6igI0D5VzC63T48tsK6ffxGFYy3rl0B/VyvHdfqe/vcw44zn6HRjF2q01DXV2NeSBZuJL+diclAcB+2jhrjha9iHWxxkJuxwFl76bAfhVdtNE6yC0It+aUtJLPT1ppcviGKpIyN1w6pGvWxk1pV+Pf6CdqU1FK05FeSPK+f34bSgIOin/DCNN6oBFgX2V5H/+Gf290bmlT9YGVSNZ0Y/HCK3Cetl3A+1j4YtbyANA3ju5mWeKeG8svzfphVRuOlKtwL+pVSrcnJuLIJqf4Nsq3PBAaPt9xzHk5vkmVfaMftQU0OXrgYhP2455SuuhpJe4LG3uyncRAXCK1AX7OoDI5jY6C4pZM00Vv+FOu5BYZLn28vr73B/rHBMzjnOCiouLbrYiCSL9VGtLcPTx4haoTWbm7fZSakyUhITI6M= alissonoliveira@ALISSON"

  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 192.168.88.10 cicd.4labs.example cicd
        - 192.168.88.20	cicd-tools.4labs.example cicd-tools 
        - 192.168.88.30 k3s.4labs.example k3s
        - 192.168.88.40 gitlab-ci.4labs.example gitlab-ci

    - name: Adiciona usuario suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criar usuário Devops
      user:
        name: "devops"
        shell: /bin/bash
        home: "/home/devops"
        state: present
        createhome: yes

    - name: Garantir que o usuário devops pode usar sudo sem senha
      lineinfile:
        path: /etc/sudoers
        line: 'devops ALL=(ALL) NOPASSWD:ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Adicionar chave pública ao arquivo authorized_keys
      authorized_key:
        user: devops
        state: present
        key: "{{ ssh_public_key }}"

    - name: Adiciona usuario jenkins
      user:
        name: jenkins
        shell: /bin/bash

    - name: Instala pacotes que permitem que o apt seja usado sobre HTTPS
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - snapd
        - git
        - vim
        - python3-docker

    - name: Faz o download do script para instalação do Docker
      get_url:
        url: https://get.docker.com/
        dest: /tmp/get_docker.sh
        mode: '0755'

    - name: Executa o script para instalação do Docker
      shell: "sh /tmp/get_docker.sh"
      
     
    - name: Criando o arquivo daemon.json
      copy:
        src: files/daemon.json
        dest: /etc/docker/
        owner: root
        group: root
        mode: '0644'

    - name: Reinicia o Docker
      service:
        name: docker
        daemon_reload: yes
        state: restarted

    - name: Baixar e instalar kubectl
      shell: |
        echo "Baixando o kubectl"
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        echo "Tornando kubectl executável"
        chmod +x kubectl
        echo "Movendo kubectl para /usr/local/bin"
        mv kubectl /usr/local/bin/
      args:
        chdir: /tmp  # Define o diretório de trabalho para evitar problemas de caminho

    - name: Verificar se kubectl está instalado
      command: kubectl version --client
      register: kubectl_version
      failed_when: kubectl_version.rc != 0
      changed_when: False

    - name: Exibir versão do kubectl
      debug:
        msg: "kubectl version: {{ kubectl_version.stdout }}"

    - name: /var/lib/jenkins/.kube
      file:
        path: /var/lib/jenkins/.kube
        state: directory
        owner: jenkins
        group: jenkins

