version: "3"

services:
  server:
    container_name: 'gitea-server'
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - devops
    volumes:
      - ./gitea:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"

  jenkins-ci-server:
    container_name: 'jenkins-ci-server'
    image: jenkins/jenkins:lts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Duser.timezone=America/Sao_Paulo -Djava.util.logging.config.file=/var/jenkins_home/log.properties -Dfile.encoding=UTF-8
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - devops
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - "8080:8080"
      - "50000:50000"

  k3s:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    command: server --disable=traefik
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    networks:
      - devops
    environment:
      - K3S_TOKEN=12345
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ./k3s-server:/var/lib/rancher/k3s
      - .:/output
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 6443:6443
      - 80:80
      - 443:443

  agent:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    tmpfs:
      - /run
      - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    networks:
      - devops
    restart: always
    environment:
      - K3S_URL=https://k3s:6443
      - K3S_TOKEN=12345

  sonarqube:
    image: sonarqube:9.6.1-community
    volumes:
      - ./sonarqube/sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube/sonarqube_logs:/opt/sonarqube/logs
      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
    ports:
      - "9000:9000"
    networks:
      - devops

  nexus:
    image: sonatype/nexus3
    volumes:
      - ./nexus:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    networks:
      - devops

networks:
  devops:
    external: true
