server {
    listen 80;
    server_name sonarqube.devops.local;

    location / {
        proxy_pass http://sonarqube:9000;  
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name gitea.devops.local;

    location / {
        proxy_pass http://gitea:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }
}
# stream {
#     server {
#         listen 2222;  # Porta SSH externa
#         proxy_pass gitea:22;  # Redireciona para o serviço Gitea
#     }
# }


server {
    listen 80;
    server_name jenkins.devops.local;

    location / {
        proxy_pass http://jenkins:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }
}

# Para os agentes Jenkins (porta 50000)
server {
    listen 50000;
    server_name jenkins.devops.local;

    location / {
        proxy_pass http://jenkins:50000;  # Direciona para o Jenkins na porta 50000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Para o Nexus na porta 8081
server {
    listen 80;
    server_name nexus.devops.local;

    location / {
        proxy_pass http://nexus:8081;  # Direciona para o Nexus na porta 8081
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Para o Nexus na porta 8082
server {
    listen 8082;
    server_name nexus.devops.local;

    location / {
        proxy_pass http://nexus:8082;  # Direciona para o Nexus na porta 8082
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Para o Nexus na porta 8083
server {
    listen 8083;
    server_name nexus.devops.local;

    location / {
        proxy_pass http://nexus:8083;  # Direciona para o Nexus na porta 8083
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
